### ISSUE TITLE
Why LGPL license?

### ISSUE THREAD

**Issue by frostney** [ev1313/Pascal-SDL-2-Headers#22]
First off, I want to thank you again for your efforts in providing SDL2 bindings for Pascal. But I can't get my head around why you chose LGPL as its license. SDL 2.0 itself use the zlib license, only SDL 1.2 used LGPL. The SDL 1.2 Pascal headers itself used MPL. Lazarus and FreePascal use LGPL, but with a static linking exception.

Where I'm a bit concerned is what it means when I want to make something that's based on these headers, like say a game engine, it seems to me that the game engine will need to be licensed under LGPL respectively.

I'm also not sure what it means in terms of usage in an application. LGPL says that an LGPL-ed program can be distributed if it's not derivate work which means it needs to link dynamically. But the headers itself don't provide the library (SDL itself does) and are therefore part of the application.

I would be grateful if you could clear up these concerns for me.

**Comment by ev1313** [comment]
Yeah, makes sense. At the time I created these headers I simply created all my code either LGPL or GPL, I simply didn't thought about it.

As you stated above, LGPL for headers should be roughly equivalent to GPL. Since I know people who want to create commercial software with these headers I decided to change the license to MPL.
