### ISSUE TITLE
Missing SDL_Free()

### ISSUE THREAD

**Issue by g00r00** [ev1313/Pascal-SDL-2-Headers#27]
Sorry if this is not the case, but I downloaded your headers tonight and I was not able to find SDL_Free() used to free the UTF8 clipboard data.  Is it missing or am I just missing it?  Thanks!

**Comment by Free-Pascal-meets-SDL-Website** [comment]
To my knowledge there hasn't been a function SDL_Free in SDL 1.2 or SDL 
2.0.

Am 06.02.2016 um 10:08 schrieb g00r00:

**Comment by g00r00** [comment]
There was at least in some form, including the original headers for Pascal by Sam Lantinga.  You can see reference to it on the Wiki for the Clipboard API (the description says it must be freed by calling SDL_Free() ).

https://wiki.libsdl.org/SDL_GetClipboardText

**Comment by ev1313** [comment]
I don't find it in the documentation http://wiki.libsdl.org/SDL_FreeSurface?action=fullsearch&context=180&value=SDL_Free&titlesearch=Titel

**Comment by Free-Pascal-meets-SDL-Website** [comment]
Sorry, my fault. SDL_free is indeed a SDL 2.0 function. For some reason 
it is not found in the api documentation. It is located in SDL_stdinc.h.

SDL_free just covers the corresponding C function "free" (void free 
(void * ptr);). Since we don't use C but Pascal, it should be safe to 
use the corresponding Pascal function, which would be "dispose".


Am 06.02.2016 um 14:00 schrieb g00r00:

**Comment by ev1313** [comment]
Then you should use dispose, if necessary.
