### ISSUE TITLE
missing some core units

### ISSUE THREAD

**Issue by JazzMaster** [ev1313/Pascal-SDL-2-Headers#57]
all im seeing is the C but core primitives do exist. They should be here. I shouldnt have to rewrite them. Shipped with SDL, not separately although some have.

**Comment by ev1313** [comment]
Could you please clarify which "core primitives" you need/are in the C headers, but not implemented?

Some structs are only defined in the source code of SDL and therefore not implemented. (These are the empty records, which are just implemented because of typesafety, as the SDL methods only return pointers to them and it's not intended using them directly.)
