### ISSUE TITLE
Returning PAnsiChar instead of PChar

### ISSUE THREAD

**Issue by piXelicidio** [ev1313/Pascal-SDL-2-Headers#69]
Hi,
On this file: https://github.com/ev1313/Pascal-SDL-2-Headers/blob/master/sdlfilesystem.inc

SDL_GetBasePath()
SDL_GetPrefPat()

Both functions are currently returning PChar, but that was giving me many headaches with unreadable foreign language strings, I just changed both to PAnsiChar on my fork and everything works fine since then. 
Specs: Windows 7 Pro 64bits, Delphi XE3 and 10.2 developing Win32 application.

I have not better arguments to suggest a change. That's what I let this here as a suggestion or comment.

Regards.

**Comment by Free-Pascal-meets-SDL-Website** [comment]
According to this discussion:

https://stackoverflow.com/questions/1803426/difference-between-pansichar-and-pchar

PChar is not interpreted as PAnsiChar by Delphi since version Delphi 
2009, so this also applies to XE3.

I would appreciate if you could open a pull request with your updated 
function declarations?

Best regards

**Comment by piXelicidio** [comment]
Ok, I did it. (Is my second time ever contributing :-o ) I really don't know if I have (and how) to put conditional directives for Delphi versions lower than 2009, if that is needed.

**Comment by Free-Pascal-meets-SDL-Website** [comment]
Thank you very much!

I would guess, it is not needed to set such cond. directives since by 
making clear the function returns PAnsiChar it is clear for any version 
of Delphi what you will get exactly. - Although I don't know since what 
(old) version of Delphi PAnsiChar itself is declared (but there were 
never any complaints from Delphi users about this here). Nevertheless, a 
simple PAnsiChar = PChar in these particular cases would do the trick.

By the way, if you want to have a look which delphi cond. dirs. are 
available, have a look into the jedi.inc.

Best regards

**Comment by ev1313** [comment]
Thanks for your contribution @piXelicidio
